config/routes.rb
Rails.application.routes.draw do

  resources :product_details
  resources :quote_details, :products

  authenticated :user do
    root to: 'home#index', as: 'home'
  end

  unauthenticated :user do
    root 'home#index'
  end

  # TODO: Define routes for the Admin auth and unauth paths. i.e. a dashboard or sign in???
  # root :to => 'business_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Business' }, :as => "business_root"
  # root :to => 'lender_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Lender' }, :as => "lender_root"

  resources :sales, :quotes, :questionaires

  get 'home/index', to: 'home#index'
  get 'home/exit', to: 'home#exit'
  get 'home/pending', to: 'home#pending'

  get 'quotes/', to: 'quotes#show_quote'

  post 'products/send_quote_request', to: 'products#send_quote_request'

  devise_for :users,  controllers: {
                        sessions: 'users/sessions',
                        registrations: 'users/registrations',
                        confirmations: 'users/confirmations'
                      }

  resources :update, :path => "/users/sessions"

  devise_for :admins, controllers: {
                        sessions: 'admins/sessions',
                        registrations: 'admins/registrations',
                        confirmations: 'admins/confirmations'
                    }

  devise_scope :admin do
    get 'admins/signed_up', to: 'admins/registrations#index'
    match 'admins/get_approved_users/:approved/:buttonId', to: 'admins/registrations#get_approved_users', via: [:get]
    put 'admins/approve_user', to: 'admins/registrations#approve_user'

    get 'admins/products/index', to: 'admins/products#index'
    get 'admins/products/new', to: 'admins/products#new'
    post 'admins/products/create', to: 'admins/products#create'
    delete 'admins/products/:id', to: 'admins/products#destroy', as: 'destroy_admin_product'

    get 'admins/products/:product_id/product_details/:id/edit', to: 'admins/product_details#edit', as: 'edit_admin_product_detail'
    post 'admins/product_details/create', to: 'admins/product_details#create'
    # put 'admins/products/:product_id/product_details/:id', to: 'admins/product_details#update', as: 'update_admin_product_detail'
    put 'admins/product_details/:id', to: 'admins/product_details#update', as: 'update_admin_product_detail'
    delete 'admins/product_details/destroy/:id', to: 'admins/product_details#destroy', as: 'destroy_admin_product_detail'
  end


end

app/models/quote.rb
class Quote < ActiveRecord::Base
  before_save :default_values

  belongs_to :user
  has_one :quote_detail
  has_one :questionaire
  has_many :products
  has_many :requester_types
  has_many :status_types

  accepts_nested_attributes_for :questionaire
  accepts_nested_attributes_for :quote_detail

  :quote_type
  :user_id
  :status_type_id
  :created_at
  :updated_at

  def default_values
    self.status_type_id = 1
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  load_and_authorize_resource
  before_action :set_quote, only: [:show, :update, :destroy]

  add_breadcrumb "Home", :home_index_path

  # GET /quotes
  # GET /quotes.json
  def index
    add_breadcrumb "Your Quotes"

    if current_admin
      @quotes = Quote.all
      @users = User.all
    else
      if user_signed_in? && current_user != []
        @quotes = current_user.quotes.all
      else
        respond_to do |format|
          format.html { redirect_to home_index_url, notice: "There are no quotes created under your account" }
          format.json { render notice: "There are no quotes created under your account", status: :unprocessable_entity }
        end
      end
    end
  end

  def show_quote
    add_breadcrumb "View Quote"
    respond_to do |format|
      format.js
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    add_breadcrumb "Create a Quote"

    @quote = Quote.new
    @quote.quote_detail.questionaire.build

  end

  # GET /quotes/1/edit
  def edit
    add_breadcrumb "Edit a Quote"
    # TODO Add to before_action, right?!
    @quote = Quote.find(params[:id])
    @questionaire = @quote.questionaire
    @quote_detail = @quote.quote_detail
    # @quote_detail = @quote.build_quote_detail
    @product = Product.find_by(id: @quote.product_id)

  end

  # POST /quotes
  # POST /quotes.json
  def create

    if current_admin.blank? && current_user.blank?
      flash[:notice] = 'You must be logged in to send a quote.'
      redirect_to home_index_path
    else

      @quote = current_user.quotes.build(quote_params)

      respond_to do |format|
        if @quote.save
          format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
          format.json { render :show, status: :created, location: @quote }
        else
          format.html { render :new }
          format.json { render json: @quote.errors, status: :unprocessable_entity }
        end
      end

    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      # params.fetch(:quote)
      params.require(:quote).permit(:quote_type, :user_id, :approved, :pending, :rejected, :product_id, quote_detail_attributes: [:quote_comments], questionaire_attributes: [ :user_id, :quote_id, :product_type, :comments])
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_edit.html.erb
<div class="row">
  <h2>Edit Quote Request</h2>
     <%= form_for(@quote, html: { role: "form", class: "form" }) do |f| %>
     <br />
       <% if admin_signed_in? %>
         <div class="form-group">
           <%= f.label :quote_type %>
           <%= f.text_field :quote_type, class: "form-control" %>
         </div>
         <div class="form-group">
         <%= f.label :status, class: "col-sm-6" %>
         <div class="col-sm-12 col-lg-12">
            <%= f.collection_select :status_type_id, StatusType.order(:name), :id, :name %>
         </div>
        </div>
       <% end %>
       <div class="form-group">
         <%= f.hidden_field :user_id, value: @quote.user_id %>
         <!-- <% f.hidden_field :quote_type, value: @quote.quote_type %> -->
       </div>
       <%= f.fields_for(:questionaire, html: { role: "form", class: "form" } ) do |q| %>
         <div class="form-group">
           <%= q.hidden_field :quote_id, value: @quote.id %>
           <%= q.hidden_field :user_id, value: @quote.user_id %>
           <%= q.hidden_field :product_type, value: @quote.questionaire.product_type %>
           <%= q.text_area :comments, class: "form-control", placeholder: "Type your quote request here" %>
         </div>
       <% end %>
       <br />
       <hr>
       <br />
       <div class="modal-footer">
           <%= f.submit "Submit for Quote", class: "btn btn-primary" %>
       </div>
   <% end %>
</div>

app/views/quotes/_fire_door_inspection.html.erb
<!-- Modal -->
<div id="fire_door_inspection" role="dialog"  class="modal fade">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" data-dismiss="modal" aria-hidden="true" class="close modal-close"><i class="icon s7-close"></i></button>
      <h3 class="modal-title">Cameras and Security Systems</h3>
    </div>
    <div class="modal-body">
      <h4>Services we offer</h4>
      <ul>
        <li>
          Security Assessments
        </li>
        <li>
          Security Systems
        </li>
        <li>
          Camera Systems
        </li>
      </ul>
      <%= form_for(@quote, html: { role: 'form', class: 'form'}) do |f| %>
      <div class="form-group">
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :quote_type, value: "fire door inspection" %>
        <%= f.hidden_field :pending, value: "true" %>
      </div>
        <%= f.fields_for(:quote_detail) do |qd| %>
        <%= qd.hidden_field :quote_comments, value: "Details created!" %>
      <% end %>
        <%= f.fields_for(:questionaire) do |q| %>
        <%= q.hidden_field :product_type, value: "fire door inspection" %>
        <%= q.label 'Requests'  %>
        <%= q.text_area :comments, class: "form-control", placeholder: "Type your requests here" %>
      <% end %>
    </div>
    <div class="modal-footer">
      <button type="button" data-dismiss="modal" class="btn btn-default modal-close">Cancel</button>
      <%= f.submit "Submit for Quote", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/quotes/_form.html.erb
 <div class="row">
   <h2>Send a Quote Request to EAHS</h2>
   <p>
     Tell us what you would like included in your quote. We will create your custom quote and contact you with the details, once completed.
   </p>
    <!-- <div class="col-md-12 col-lg-6"> -->
      <%= form_for(@quote, html: { role: "form", class: "form" }) do |f| %>
      <br />
        <% if admin_signed_in? %>
          <div class="form-group">
            <%= f.label :quote_type %>
            <%= f.text_field :quote_type, class: "form-control" %>
          </div>
          <div class="form-group">
              <%= f.label :status, class: "col-sm-6" %>
              <div class="col-sm-12 col-lg-12">
                <div class="am-checkbox inline">
                  <label>pending:</label> <%= f.check_box :pending, class: "form-control"  %>
                </div>
                <div class="am-checkbox inline">
                  <label>rejected:</label><%= f.check_box :rejected, class: "form-control" %>
                </div>
                <div class="am-checkbox inline">
                  <label>approved:</label><%= f.check_box :approved, class: "form-control" %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.hidden_field :user_id, value: @quote.user_id %>
          <!-- <% f.hidden_field :quote_type, value: @quote.quote_type %> -->
        </div>
        <%= f.fields_for(:questionaire, html: { role: "form", class: "form" } ) do |q| %>
          <div class="form-group">
            <%= q.hidden_field :user_id, value: @quote.user_id %>
            <%= q.hidden_field :product_type, value: @product.product_type %>
            <%= q.text_area :comments, class: "form-control", placeholder: "Type your quote request here" %>
          </div>
        <% end %>
        <br />
        <hr>
        <br />
        <div class="modal-footer">
            <%= f.submit "Submit for Quote", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/quotes/_locksmith.html.erb
  <div class="modal fade" id="locksmith_modal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Locksmithing Services</h4>
        </div>
        <div class="modal-body">
          <h3>Services we offer</h3>
          <ul>
            <li>
              Basic Keys - Simple Services
            </li>
            <li>
              Hardware Replacement
            </li>
            <li>
              Access Control - Design - Repair
            </li>
            <li>
              High Security Locks - Highend Services
            </li>
          </ul>
          <%= form_for(@quote) do |f| %>
            <div class="form-group">
              <%= f.hidden_field :user_id %>
              <%= f.hidden_field :quote_type, value: "locksmith" %>
              <%= f.hidden_field :pending, value: "true" %>
            </div>
            <%= f.fields_for(:questionaire) do |q| %>
              <%= q.hidden_field :product_type, value: "key repair" %>
              <%= q.label 'Requests' %>
              <%= q.text_area :comments, class: "form-control", placeholder: "Type your requests here" %>
            <% end %>
        </div>
        <div class="modal-footer">
            <%= f.submit "Submit for Quote", class: "btn btn-primary" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/quotes/_security.html.erb
  <div class="modal fade" id="security_modal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Safes</h4>
        </div>
        <div class="modal-body">
          <h3>Services we offer</h3>
          <ul>
            <li>
              Servicing
            </li>
            <li>
              Combination Change
            </li>
            <li>
              Opening and Repair
            </li>
            <li>
              Moving
            </li>
            <li>
              Sales
            </li>
          </ul>
          <%= form_for(@quote) do |f| %>
            <div class="form-group">
              <%= f.hidden_field :user_id %>
              <%= f.hidden_field :quote_type, value: "Security" %>
              <%= f.hidden_field :pending, value: "true" %>
            </div>
            <%= f.fields_for(:questionaire) do |q| %>
              <%= q.hidden_field :product_type, value: "Safe" %>
              <%= q.label "Request" %>
              <%= q.text_area :comments, class: "form-control" , placeholder: "Type your requests here" %>
            <% end %>
        </div>
        <div class="modal-footer">
            <%= f.submit "Submit for Quote", class: "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/quotes/_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <section class="quote-block">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">
              Quote Information for
              <span class="badge ">
                #  <%= @quote.id %>
              </span>
            </h3>
          </div>
          <div class="panel-body">
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Quote Type:
              </span>
                <%= @quote.quote_type %>
            </div>
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Status:
              </span>
              
            </div>
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Product Type:
              </span>
              <%= @quote.questionaire.product_type %>
            </div>
            <div class="col-sm-12 lead">
              <span class="strong-type">
                Your Comments:
              </span>
              <%= @quote.questionaire.comments %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/edit.js.erb
$("#showQuote").html("<%= escape_javascript(render partial: "edit", locals: { quote: @quote } )%>");

app/views/quotes/index.html.erb
<h1>Quote Maintenance</h1>
<table class="table table-bordered table-striped table-hover" id="quotes-table">
  <thead>
    <tr>
      <th>Quote Type</th>
      <th>Submitted By</th>
      <th>Submitted Date</th>
      <th><center>Status</center></th>
      <th>
        <center>
          <i class="glyphicon glyphicon-eye-open"></i>
        </center>
      </th>
      <% if current_admin %>
      <th>
        <center>
          <i class="glyphicon glyphicon-pencil"></i>
        </center>
      </th>
      <th>
        <center>
          <i class="glyphicon glyphicon-fire"></i>
        </center>
      </th>
      <% end %>
    </tr>
  </thead>
  <tbody class="table-hover">
    <% @quotes.each do |quote| %>
    <tr>
      <td>
        <%= quote.quote_type %>
      </td>
      <% if admin_signed_in? %>
      <td>
        <%= quote.user.first_name + " " + quote.user.last_name %>
      </td>
      <% else %>
      <td>
        <%= current_user.first_name + " " + current_user.last_name %>
      </td>
      <% end %>
      <td><%= quote.created_at.to_formatted_s(:short) %></td>
      <td>
        
      </td>
      <td>
        <center>
          <%= link_to 'View', quote_path(quote),  remote: true %>
        </center>
      </td>
      <% if current_admin %>
      <td>
        <center>
          <%= link_to 'Edit', edit_quote_path(quote),   remote: true %>
        </center>
      </td>
      <td>
        <center>
          <%= link_to 'Delete', quote, method: :delete, data: { confirm: 'Are you sure?' } %>
        </center>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>


<div id="showQuote">
</div>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/save_quote.js.erb
<% if @save == "true" %>
  // success message
<% else %>
  // Error message for save
<% end %>

app/views/quotes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <section class="quote-block">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">
              Quote Information for
              <span class="badge ">
                #  <%= @quote.id %>
              </span>
            </h3>
          </div>
          <div class="panel-body">
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Quote Type:
              </span>
                <%= @quote.quote_type %>
            </div>
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Status:
              </span>
            </div>
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Product Type:
              </span>
              <%= @quote.questionaire.product_type %>
            </div>
            <div class="col-sm-12 lead">
              <span class="strong-type">
                Your Comments:
              </span>
              <%= @quote.questionaire.comments %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

<% if current_admin %>
<%= link_to 'Edit', edit_quote_path(@quote) %> |
<% end %>
<%= link_to 'Back', quotes_path %>

app/views/quotes/show.js.erb
(function() {
  $("#showQuote").html("<%= escape_javascript(render partial: "show", locals: { quote: @quote } )%>");
})()