config/routes.rb
Rails.application.routes.draw do

  resources :product_details
  resources :quote_details, :products

  authenticated :user do
    root to: 'home#index', as: 'home'
  end

  unauthenticated :user do
    root 'home#index'
  end

  # TODO: Define routes for the Admin auth and unauth paths. i.e. a dashboard or sign in???
  # root :to => 'business_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Business' }, :as => "business_root"
  # root :to => 'lender_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Lender' }, :as => "lender_root"

  resources :sales, :quotes, :questionaires

  get 'home/index', to: 'home#index'
  get 'home/exit', to: 'home#exit'
  get 'home/pending', to: 'home#pending'

  get 'quotes/', to: 'quotes#show_quote'

  post 'products/send_quote_request', to: 'products#send_quote_request'

  devise_for :users,  controllers: {
                        sessions: 'users/sessions',
                        registrations: 'users/registrations',
                        confirmations: 'users/confirmations'
                      }

  resources :update, :path => "/users/sessions"

  devise_for :admins, controllers: {
                        sessions: 'admins/sessions',
                        registrations: 'admins/registrations',
                        confirmations: 'admins/confirmations'
                    }

  devise_scope :admin do
    get 'admins/signed_up', to: 'admins/registrations#index'
    match 'admins/get_approved_users/:approved/:buttonId', to: 'admins/registrations#get_approved_users', via: [:get]
    put 'admins/approve_user', to: 'admins/registrations#approve_user'

    get 'admins/products/index', to: 'admins/products#index'
    get 'admins/products/new', to: 'admins/products#new'
    post 'admins/products/create', to: 'admins/products#create'
    delete 'admins/products/:id', to: 'admins/products#destroy', as: 'destroy_admin_product'

    get 'admins/products/:product_id/product_details/:id/edit', to: 'admins/product_details#edit', as: 'edit_admin_product_detail'
    post 'admins/product_details/create', to: 'admins/product_details#create'
    # put 'admins/products/:product_id/product_details/:id', to: 'admins/product_details#update', as: 'update_admin_product_detail'
    put 'admins/product_details/:id', to: 'admins/product_details#update', as: 'update_admin_product_detail'
    delete 'admins/product_details/destroy/:id', to: 'admins/product_details#destroy', as: 'destroy_admin_product_detail'
  end


end

app/views/layouts/shared/_admin_navbar.html.erb
<nav class="main-nav-outer" id="primary_nav">
  <div class="container">
    <ul class="main-nav">
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <% if admin_signed_in? %>
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
            Products & Services Manager
            <span class="angle-down s7-angle-down"></span>
          </a>
          <ul role="menu" class="dropdown-menu">
            <li>
              <%= link_to "Customer Quotes", quotes_path %>
            </li>
            <li>
                <%= link_to  "Product Manager", admins_products_index_path %>
            </li>
          </ul>
        </li>
      <% end %>
      <!-- ICON -->
      <li class="small-logo">
        <%= link_to root_path, id: "#header" do %>
          <%= image_tag "EAH-Brand.png", class: "logo" %>
        <% end %>
      </li>
      <% if admin_signed_in? %>
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
            Admin Manager
            <span class="angle-down s7-angle-down"></span>
          </a>
          <ul role="menu" class="dropdown-menu">
            <li>
              <%= link_to 'Create Admin',  new_admin_registration_path %>
            </li>
            <li>
              <%= link_to 'Manage Admins',  new_admin_registration_path %>
            </li>
            <li>
              <%= link_to 'Your Settings', edit_admin_registration_path %>
            </li>
            <li>
              <%= link_to 'User Manager', admins_signed_up_path %>
            </li>
          </ul>
        </li>
      <% end %>
      <% if current_admin.blank? %>
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
            Sign In
            <span class="angle-down s7-angle-down"></span>
          </a>
          <ul role="menu" class="dropdown-menu">
            <li style="width: 600px;">
              <%= render "admins/sessions/new" %>
            </li>
          </ul>
        </li>
      <% end %>
      <% if admin_signed_in? %>
        <li>
          <%= link_to 'Sign out', destroy_admin_session_path, method: :delete %>
        </li>
      <% end %>
    </ul>
      <a class="res-nav_click hidden-xl hidden-lg" href="#">
        <i class="fa fa-bars"></i>
      </a>
    </div>
  </nav>

app/views/layouts/shared/_navbar.html.erb
<nav class="main-nav-outer" id="primary_nav" >
  <div class="container">
    <ul class="main-nav">
      <% if controller.controller_name == "home" %>
        <li>
          <a href="#header">Home</a>
        </li>
      <% else %>
        <li>
          <%= link_to "Home", root_path %>
        </li>
      <% end %>
        <li>
          <%= link_to "Services", "#service" %>
        </li>
        <li>
          <%= link_to  "Products",  "#Portfolio" %>
        </li>
      <!-- ICON -->
      <li class="small-logo">
        <%= link_to "#header"  do %>
          <%= image_tag "EAH-Brand.png", class: "logo" %>
        <% end %>
      </li>
      <!-- CHECK IF THE DUDE LOGGED IN. -->
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
            <!-- TOGGLE TEXT -->
              My EAHS
            <span class="angle-down s7-angle-down"></span>
          </a>
          <ul role="menu" class="dropdown-menu">
            <% if  current_user.blank? && current_admin.blank? %>
              <%= link_to "Register to access!", new_user_registration_path %>
            <% end %>
            <!-- ADMIN OPTIONS -->
            <!-- Removed for now -->
            <!-- USER OPTIONS -->
            <% if user_signed_in? %>
              <li>
                <%= link_to "View Open Quotes", quotes_path %>
              </li>
              <li>
                <%= link_to "Edit Account Details", edit_user_registration_path %>
              </li>
            <% end %>
          </ul>
        </li>
        <% if current_user.blank? && !@adminFlag %>
          <li>
            <%= link_to 'Sign Up',  '#register' %>
          </li>
        <% end %>
        <% if current_user.blank? &&  !@adminFlag %>
          <li class="dropdown">
            <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
              Sign In
              <span class="angle-down s7-angle-down"></span>
            </a>
            <ul role="menu" class="dropdown-menu">
              <li style="width: 600px;">
                <%= render "users/sessions/new" %>
              </li>
            </ul>
          </li>
        <% end %>
        <% if user_signed_in? %>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </li>
      <% end %>
    </ul>
    <a class="res-nav_click hidden-xl hidden-lg" href="#">
      <i class="fa fa-bars"></i>
    </a>
  </div>
</nav>