config/routes.rb
Rails.application.routes.draw do

  resources :product_details
  resources :quote_details, :products

  authenticated :user do
    root to: 'home#index', as: 'home'
  end

  unauthenticated :user do
    root 'home#index'
  end

  # TODO: Define routes for the Admin auth and unauth paths. i.e. a dashboard or sign in???
  # root :to => 'business_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Business' }, :as => "business_root"
  # root :to => 'lender_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Lender' }, :as => "lender_root"

  resources :sales, :quotes, :questionaires

  get 'home/index', to: 'home#index'
  get 'home/exit', to: 'home#exit'
  get 'home/pending', to: 'home#pending'

  get 'quotes/', to: 'quotes#show_quote'

  post 'products/send_quote_request', to: 'products#send_quote_request'

  devise_for :users,  controllers: {
                        sessions: 'users/sessions',
                        registrations: 'users/registrations',
                        confirmations: 'users/confirmations'
                      }

  resources :update, :path => "/users/sessions"

  devise_for :admins, controllers: {
                        sessions: 'admins/sessions',
                        registrations: 'admins/registrations',
                        confirmations: 'admins/confirmations'
                    }

  devise_scope :admin do
    get 'admins/signed_up', to: 'admins/registrations#index'
    match 'admins/get_approved_users/:approved/:buttonId', to: 'admins/registrations#get_approved_users', via: [:get]
    put 'admins/approve_user', to: 'admins/registrations#approve_user'

    get 'admins/products/index', to: 'admins/products#index'
    get 'admins/products/new', to: 'admins/products#new'
    post 'admins/products/create', to: 'admins/products#create'
    delete 'admins/products/:id', to: 'admins/products#destroy', as: 'destroy_admin_product'

    get 'admins/products/:product_id/product_details/:id/edit', to: 'admins/product_details#edit', as: 'edit_admin_product_detail'
    post 'admins/product_details/create', to: 'admins/product_details#create'
    # put 'admins/products/:product_id/product_details/:id', to: 'admins/product_details#update', as: 'update_admin_product_detail'
    put 'admins/product_details/:id', to: 'admins/product_details#update', as: 'update_admin_product_detail'
    delete 'admins/product_details/destroy/:id', to: 'admins/product_details#destroy', as: 'destroy_admin_product_detail'
  end


end

app/models/quote_detail.rb
class QuoteDetail < ActiveRecord::Base
  belongs_to :quote
  has_many :users, through: :quote

  :quote_id
  :quote_comments
  :approved_by
  :rejected_by
  :rejected_reason
  :estimate
end

app/controllers/quote_details_controller.rb
class QuoteDetailsController < ApplicationController
  before_action :set_quote_detail, only: [:show, :edit, :update, :destroy]

  # GET /quote_details
  # GET /quote_details.json
  def index
    @quote_details = QuoteDetail.all
  end

  # GET /quote_details/1
  # GET /quote_details/1.json
  def show
  end

  # GET /quote_details/new
  def new
    @quote_detail = current_user.quotes.quote_details.new
  end

  # GET /quote_details/1/edit
  def edit
  end

  # POST /quote_details
  # POST /quote_details.json
  def create
    @quote_detail = QuoteDetail.new(quote_detail_params)

    respond_to do |format|
      if @quote_detail.save
        format.html { redirect_to @quote_detail, notice: 'Quote detail was successfully created.' }
        format.json { render :show, status: :created, location: @quote_detail }
      else
        format.html { render :new }
        format.json { render json: @quote_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quote_details/1
  # PATCH/PUT /quote_details/1.json
  def update
    respond_to do |format|
      if @quote_detail.update(quote_detail_params)
        format.html { redirect_to @quote_detail, notice: 'Quote detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote_detail }
      else
        format.html { render :edit }
        format.json { render json: @quote_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quote_details/1
  # DELETE /quote_details/1.json
  def destroy
    @quote_detail.destroy
    respond_to do |format|
      format.html { redirect_to quote_details_url, notice: 'Quote detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote_detail
      @quote_detail = QuoteDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_detail_params
      params.require(:quote_detail).permit(:quote_id, :quote_comments, :approved_by, :rejected_by, :rejected_reason, :estimate)
    end
end

app/helpers/quote_details_helper.rb
module QuoteDetailsHelper
end

app/views/quote_details/_form.html.erb
<%= form_for(@quote_detail) do |f| %>
  <% if @quote_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote_detail.errors.count, "error") %> prohibited this quote_detail from being saved:</h2>

      <ul>
      <% @quote_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quote_details/edit.html.erb
<h1>Editing Quote Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote_detail %> |
<%= link_to 'Back', quote_details_path %>

app/views/quote_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quote Details</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quote_details.each do |quote_detail| %>
      <tr>
        <td><%= link_to 'Show', quote_detail %></td>
        <td><%= link_to 'Edit', edit_quote_detail_path(quote_detail) %></td>
        <td><%= link_to 'Destroy', quote_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote detail', new_quote_detail_path %>

app/views/quote_details/new.html.erb
<h1>New Quote Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', quote_details_path %>

app/views/quote_details/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <section class="quote-block">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">
              Quote Information for
              <span class="badge ">
                #  <%= @quote.id %>
              </span>
            </h3>
          </div>
          <div class="panel-body">
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Quote Type:
              </span>
                <%= @quote.quote_type %>
            </div>
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Status:
              </span>
              <% if @quote.rejected %>
                <span class="label label-danger">
                  Rejected!
                </span>
              <% end %>
              <% if @quote.pending %>
                <span class="label label-warning">
                  Pending...
                </span>
              <% end %>
              <% if @quote.approved %>
                <span class="label label-success">
                  Approved
                </span>
              <% end %>
            </div>
            <div class="col-sm-6 lead">
              <span class="strong-type">
                Product Type:
              </span>
              <%= @quote.questionaire.product_type %>
            </div>
            <div class="col-sm-12 lead">
              <span class="strong-type">
                Your Comments:
              </span>
              <%= @quote.questionaire.comments %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

<% if current_admin %>
<%= link_to 'Edit', edit_quote_path(@quote) %> |
<% end %>
<%= link_to 'Back', quotes_path %>

<%= link_to 'Edit', edit_quote_detail_path(@quote_detail) %> |
<%= link_to 'Back', quote_details_path %>